apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
spec:
  selector:
    matchLabels:
      app: echo1
  replicas: 3
  template:
    metadata:
      labels:
        app: echo1
        version: v1
    spec:
      containers:
      - name: hello
        image: ilkiformation/web-echo:v1
        env:
        - name: TEXT
          value: echo1
        - name: NEXT
          value: "echo2:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo1
  labels:
    app: echo1
spec:
  selector:
    app: echo1
  ports:
  - name: http
    port: 8080
    targetPort: 8080




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo2
spec:
  selector:
    matchLabels:
      app: echo2
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: echo2
        version: v1
    spec:
      containers:
      - name: world
        image: ilkiformation/web-echo:v1
        env:
        - name: TEXT
          value: echo2
        - name: NEXT
          value: "echo3:8080"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo2
  labels:
    app: echo2
spec:
  selector:
    app: echo2
  ports:
  - name: http
    port: 8080
    targetPort: 8080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo3
spec:
  selector:
    matchLabels:
      app: echo3
  replicas: 3
  template:
    metadata:
      labels:
        app: echo3
        version: v1
    spec:
      containers:
      - name: echo3
        image: ilkiformation/web-echo:v1
        env:
        - name: TEXT
          value: echo3
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo3
  labels:
    app: echo3
spec:
  selector:
    app: echo3
  ports:
  - name: http
    port: 8080
    targetPort: 8080
